import joi from "joi";

export const adressModel = joi.object({
  street: joi.string().min(3).required(), //Rua
  number: joi.number().min(1).required(), //Numero
  complement: joi.string(), // Complemento
  postalCode: joi.string().pattern(new RegExp('^[0-9]{5}[\-]?[0-9]{3}$')).required(), //CEP: (no seguinte padrão) 00000-000
  district: joi.string().min(3).required(), //Bairro: Centro, Jd.Liberdade, Asa Norte...
  city: joi.string().min(3).required(), //Cidade: Rondonópolis, São Paulo, Brasília...
  state: joi.string().min(2).required(), //Estado: MT, SP, DF...
  type: joi.string().min(3).required(), //Tipo: house, apartment, commerce...
});
